name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "socketry2"
          heroku_email: "jack-mead@hotmail.co.uk"
          healthcheck: "https://socketry2.herokuapp.com/healthcheck"
          usedocker: true